import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import Galaxy from "./components/Galaxy";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Portofolio - Apaa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${poppins.variable} ${inter.variable} antialiased leading-8 overflow-x-hidden bg-gray-50 dark:bg-black text-black dark:text-white transition-colors duration-500 `}>
        <Galaxy/>
        {children}
      </body>
    </html>
  );
}
